# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: INFO
    org.hibernate.SQL: INFO
    com.bassi.tmapp: DEBUG
    javax.management.remote.rmi: ERROR
    org.openqa.selenium: ERROR
    jdk.internal.httpclient: ERROR

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/tmapp
    username: tmapp
    password: admin
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev
    enabled: true
  mail:
    host: smtp.zeptomail.in
    port: 587
    username: emailapikey
    password: PHtE6r1YF+Hj2m57pkRRtPLtEM+iZ44p/+4xLAhP5t5DCaMDH00A/dwtkDfkrk1+B6RDR6OczN1q5L/KsriGczntN29PDWqyqK3sx/VYSPOZsbq6x00bsV4cdkPYVYTqc9Jj1SDeu9bTNA==
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
          starttls:
            enable: true
            required: true
    from: support@trademarx.in
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8080
  # make sure requests the proxy uri instead of the server one
  forward-headers-strategy: native

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200, http://localhost:6700'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NmJmMGNmN2MxODlhOGQ1Y2E4YzQxYWRmNWFhOTQ3ZTEzM2E3MTE4MzRmYjkwYmQyYWY5ZTNhM2NkOWYxOTZkNDMxZWE2MDNiOTcyNDVmYzU2MjEwNmU5MDI2NDA4Nzg2YjBiOWI2YTlmNzA0NjBiNzdlMGE5MjI4YmE3N2I5ZDc=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://localhost:4200
    from: support@trademarx.in
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
  captcha:
    url: ishanbassi23@gmail.com
    userId: Gm0iz1chYVbJ1En2QzG8
    apiKey: https://api.apitruecaptcha.org/one/gettext
  admin-notifications-email-address:
    - ishanbassi23@gmail.com
  razorpay:
    key-id: rzp_test_RGemw0gmJ3U08S
    key-secret: S3TvQC6miKsJlK6dfz0t1Vr6
    company-name: Trademarx
    currency: INR
    base-url: https://api.razorpay.com/v1
  google-captcha:
    site-key: 6LcTLeYrAAAAACoTM9NIteBSX7ucj0ZRqDmQJF82
    secret-key: 6LcTLeYrAAAAAC1u_J-lffNhAIeLbdcG71JB3v4Z
    server-verify-url: https://www.google.com/recaptcha/api/siteverify
file-upload-base-path: /opt/application/staging/files/
pdf-file-base-path: /opt/application/staging/pdfs/
errors-file-base-path: /opt/application/staging/errors/
document-base-path: /opt/application/staging/documents/
