export enum DocumentStatus {
  UPLOADED = 'UPLOADED',

  UNDER_REVIEW = 'UNDER_REVIEW',

  APPROVED = 'APPROVED',

  REJECTED = 'REJECTED',

  REUPLOAD_REQUESTED = 'REUPLOAD_REQUESTED',

  DELETED = 'DELETED',
}
