export enum PhoneticAlgorithmType {
  SOUNDEX = 'SOUNDEX',

  METAPHONE = 'METAPHONE',

  INDIAN_PHONETIC = 'INDIAN_PHONETIC',

  DOUBLE_METAPHONE = 'DOUBLE_METAPHONE',

  TRIPLE_METAPHONE = 'TRIPLE_METAPHONE',

  OTHER = 'OTHER',
}
