export enum TrademarkStatus {
  DRAFT = 'DRAFT',

  FILED = 'FILED',

  UNDER_EXAMINATION = 'UNDER_EXAMINATION',

  OBJECTED = 'OBJECTED',

  EXAMINATION_REPLY_FILED = 'EXAMINATION_REPLY_FILED',

  ACCEPTED_AND_ADVERTISED = 'ACCEPTED_AND_ADVERTISED',

  OPPOSED = 'OPPOSED',

  HEARING = 'HEARING',

  REGISTERED = 'REGISTERED',

  ABANDONED = 'ABANDONED',

  WITHDRAWN = 'WITHDRAWN',

  REJECTED = 'REJECTED',

  EXPIRED = 'EXPIRED',

  RENEWED = 'RENEWED',
}
