package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class LeadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAllPropertiesEquals(Lead expected, Lead actual) {
        assertLeadAutoGeneratedPropertiesEquals(expected, actual);
        assertLeadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAllUpdatablePropertiesEquals(Lead expected, Lead actual) {
        assertLeadUpdatableFieldsEquals(expected, actual);
        assertLeadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAutoGeneratedPropertiesEquals(Lead expected, Lead actual) {
        assertThat(expected)
            .as("Verify Lead auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadUpdatableFieldsEquals(Lead expected, Lead actual) {
        assertThat(expected)
            .as("Verify Lead relevant properties")
            .satisfies(e -> assertThat(e.getFullName()).as("check fullName").isEqualTo(actual.getFullName()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getCity()).as("check city").isEqualTo(actual.getCity()))
            .satisfies(e -> assertThat(e.getBrandName()).as("check brandName").isEqualTo(actual.getBrandName()))
            .satisfies(e -> assertThat(e.getSelectedPackage()).as("check selectedPackage").isEqualTo(actual.getSelectedPackage()))
            .satisfies(e -> assertThat(e.getTmClass()).as("check tmClass").isEqualTo(actual.getTmClass()))
            .satisfies(e -> assertThat(e.getComments()).as("check comments").isEqualTo(actual.getComments()))
            .satisfies(e -> assertThat(e.getContactMethod()).as("check contactMethod").isEqualTo(actual.getContactMethod()))
            .satisfies(
                e ->
                    assertThat(e.getCreatedDate())
                        .as("check createdDate")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getCreatedDate())
            )
            .satisfies(
                e ->
                    assertThat(e.getModifiedDate())
                        .as("check modifiedDate")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getModifiedDate())
            )
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getLeadSource()).as("check leadSource").isEqualTo(actual.getLeadSource()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadUpdatableRelationshipsEquals(Lead expected, Lead actual) {
        assertThat(expected)
            .as("Verify Lead relationships")
            .satisfies(e -> assertThat(e.getAssignedTo()).as("check assignedTo").isEqualTo(actual.getAssignedTo()));
    }
}
