package com.bassi.tmapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhoneticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsAllPropertiesEquals(Phonetics expected, Phonetics actual) {
        assertPhoneticsAutoGeneratedPropertiesEquals(expected, actual);
        assertPhoneticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsAllUpdatablePropertiesEquals(Phonetics expected, Phonetics actual) {
        assertPhoneticsUpdatableFieldsEquals(expected, actual);
        assertPhoneticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsAutoGeneratedPropertiesEquals(Phonetics expected, Phonetics actual) {
        assertThat(actual)
            .as("Verify Phonetics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsUpdatableFieldsEquals(Phonetics expected, Phonetics actual) {
        assertThat(actual)
            .as("Verify Phonetics relevant properties")
            .satisfies(a -> assertThat(a.getSanitizedTm()).as("check sanitizedTm").isEqualTo(expected.getSanitizedTm()))
            .satisfies(a -> assertThat(a.getPhoneticPk()).as("check phoneticPk").isEqualTo(expected.getPhoneticPk()))
            .satisfies(a -> assertThat(a.getPhoneticSk()).as("check phoneticSk").isEqualTo(expected.getPhoneticSk()))
            .satisfies(a -> assertThat(a.getComplete()).as("check complete").isEqualTo(expected.getComplete()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsUpdatableRelationshipsEquals(Phonetics expected, Phonetics actual) {
        assertThat(actual)
            .as("Verify Phonetics relationships")
            .satisfies(a -> assertThat(a.getTrademark()).as("check trademark").isEqualTo(expected.getTrademark()));
    }
}
