package com.bassi.tmapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhoneticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsAllPropertiesEquals(Phonetics expected, Phonetics actual) {
        assertPhoneticsAutoGeneratedPropertiesEquals(expected, actual);
        assertPhoneticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsAllUpdatablePropertiesEquals(Phonetics expected, Phonetics actual) {
        assertPhoneticsUpdatableFieldsEquals(expected, actual);
        assertPhoneticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsAutoGeneratedPropertiesEquals(Phonetics expected, Phonetics actual) {
        assertThat(expected)
            .as("Verify Phonetics auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsUpdatableFieldsEquals(Phonetics expected, Phonetics actual) {
        assertThat(expected)
            .as("Verify Phonetics relevant properties")
            .satisfies(e -> assertThat(e.getSanitizedTm()).as("check sanitizedTm").isEqualTo(actual.getSanitizedTm()))
            .satisfies(e -> assertThat(e.getPhoneticPk()).as("check phoneticPk").isEqualTo(actual.getPhoneticPk()))
            .satisfies(e -> assertThat(e.getPhoneticSk()).as("check phoneticSk").isEqualTo(actual.getPhoneticSk()))
            .satisfies(e -> assertThat(e.getComplete()).as("check complete").isEqualTo(actual.getComplete()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneticsUpdatableRelationshipsEquals(Phonetics expected, Phonetics actual) {
        assertThat(expected)
            .as("Verify Phonetics relationships")
            .satisfies(e -> assertThat(e.getTrademark()).as("check trademark").isEqualTo(actual.getTrademark()));
    }
}
