package com.bassi.tmapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublishedTmPhoneticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsAllPropertiesEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertPublishedTmPhoneticsAutoGeneratedPropertiesEquals(expected, actual);
        assertPublishedTmPhoneticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsAllUpdatablePropertiesEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertPublishedTmPhoneticsUpdatableFieldsEquals(expected, actual);
        assertPublishedTmPhoneticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsAutoGeneratedPropertiesEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertThat(expected)
            .as("Verify PublishedTmPhonetics auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsUpdatableFieldsEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertThat(expected)
            .as("Verify PublishedTmPhonetics relevant properties")
            .satisfies(e -> assertThat(e.getSanitizedTm()).as("check sanitizedTm").isEqualTo(actual.getSanitizedTm()))
            .satisfies(e -> assertThat(e.getPhoneticPk()).as("check phoneticPk").isEqualTo(actual.getPhoneticPk()))
            .satisfies(e -> assertThat(e.getPhoneticSk()).as("check phoneticSk").isEqualTo(actual.getPhoneticSk()))
            .satisfies(e -> assertThat(e.getComplete()).as("check complete").isEqualTo(actual.getComplete()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsUpdatableRelationshipsEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertThat(expected)
            .as("Verify PublishedTmPhonetics relationships")
            .satisfies(e -> assertThat(e.getPublishedTm()).as("check publishedTm").isEqualTo(actual.getPublishedTm()));
    }
}
