package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PublishedTmAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmAllPropertiesEquals(PublishedTm expected, PublishedTm actual) {
        assertPublishedTmAutoGeneratedPropertiesEquals(expected, actual);
        assertPublishedTmAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmAllUpdatablePropertiesEquals(PublishedTm expected, PublishedTm actual) {
        assertPublishedTmUpdatableFieldsEquals(expected, actual);
        assertPublishedTmUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmAutoGeneratedPropertiesEquals(PublishedTm expected, PublishedTm actual) {
        assertThat(actual)
            .as("Verify PublishedTm auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmUpdatableFieldsEquals(PublishedTm expected, PublishedTm actual) {
        assertThat(actual)
            .as("Verify PublishedTm relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getApplicationNo()).as("check applicationNo").isEqualTo(expected.getApplicationNo()))
            .satisfies(a -> assertThat(a.getApplicationDate()).as("check applicationDate").isEqualTo(expected.getApplicationDate()))
            .satisfies(a -> assertThat(a.getAgentName()).as("check agentName").isEqualTo(expected.getAgentName()))
            .satisfies(a -> assertThat(a.getAgentAddress()).as("check agentAddress").isEqualTo(expected.getAgentAddress()))
            .satisfies(a -> assertThat(a.getProprietorName()).as("check proprietorName").isEqualTo(expected.getProprietorName()))
            .satisfies(a -> assertThat(a.getProprietorAddress()).as("check proprietorAddress").isEqualTo(expected.getProprietorAddress()))
            .satisfies(a -> assertThat(a.getHeadOffice()).as("check headOffice").isEqualTo(expected.getHeadOffice()))
            .satisfies(a -> assertThat(a.getImgUrl()).as("check imgUrl").isEqualTo(expected.getImgUrl()))
            .satisfies(a -> assertThat(a.getTmClass()).as("check tmClass").isEqualTo(expected.getTmClass()))
            .satisfies(a -> assertThat(a.getJournalNo()).as("check journalNo").isEqualTo(expected.getJournalNo()))
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a -> assertThat(a.getUsage()).as("check usage").isEqualTo(expected.getUsage()))
            .satisfies(a -> assertThat(a.getAssociatedTms()).as("check associatedTms").isEqualTo(expected.getAssociatedTms()))
            .satisfies(a -> assertThat(a.getTrademarkStatus()).as("check trademarkStatus").isEqualTo(expected.getTrademarkStatus()))
            .satisfies(a ->
                assertThat(a.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedDate())
            )
            .satisfies(a ->
                assertThat(a.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getModifiedDate())
            )
            .satisfies(a -> assertThat(a.getRenewalDate()).as("check renewalDate").isEqualTo(expected.getRenewalDate()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPageNo()).as("check pageNo").isEqualTo(expected.getPageNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmUpdatableRelationshipsEquals(PublishedTm expected, PublishedTm actual) {
        assertThat(actual)
            .as("Verify PublishedTm relationships")
            .satisfies(a -> assertThat(a.getTmAgent()).as("check tmAgent").isEqualTo(expected.getTmAgent()));
    }
}
