package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PublishedTmAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmAllPropertiesEquals(PublishedTm expected, PublishedTm actual) {
        assertPublishedTmAutoGeneratedPropertiesEquals(expected, actual);
        assertPublishedTmAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmAllUpdatablePropertiesEquals(PublishedTm expected, PublishedTm actual) {
        assertPublishedTmUpdatableFieldsEquals(expected, actual);
        assertPublishedTmUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmAutoGeneratedPropertiesEquals(PublishedTm expected, PublishedTm actual) {
        assertThat(expected)
            .as("Verify PublishedTm auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmUpdatableFieldsEquals(PublishedTm expected, PublishedTm actual) {
        assertThat(expected)
            .as("Verify PublishedTm relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDetails()).as("check details").isEqualTo(actual.getDetails()))
            .satisfies(e -> assertThat(e.getApplicationNo()).as("check applicationNo").isEqualTo(actual.getApplicationNo()))
            .satisfies(e -> assertThat(e.getApplicationDate()).as("check applicationDate").isEqualTo(actual.getApplicationDate()))
            .satisfies(e -> assertThat(e.getAgentName()).as("check agentName").isEqualTo(actual.getAgentName()))
            .satisfies(e -> assertThat(e.getAgentAddress()).as("check agentAddress").isEqualTo(actual.getAgentAddress()))
            .satisfies(e -> assertThat(e.getProprietorName()).as("check proprietorName").isEqualTo(actual.getProprietorName()))
            .satisfies(e -> assertThat(e.getProprietorAddress()).as("check proprietorAddress").isEqualTo(actual.getProprietorAddress()))
            .satisfies(e -> assertThat(e.getHeadOffice()).as("check headOffice").isEqualTo(actual.getHeadOffice()))
            .satisfies(e -> assertThat(e.getImgUrl()).as("check imgUrl").isEqualTo(actual.getImgUrl()))
            .satisfies(e -> assertThat(e.getTmClass()).as("check tmClass").isEqualTo(actual.getTmClass()))
            .satisfies(e -> assertThat(e.getJournalNo()).as("check journalNo").isEqualTo(actual.getJournalNo()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getUsage()).as("check usage").isEqualTo(actual.getUsage()))
            .satisfies(e -> assertThat(e.getAssociatedTms()).as("check associatedTms").isEqualTo(actual.getAssociatedTms()))
            .satisfies(e -> assertThat(e.getTrademarkStatus()).as("check trademarkStatus").isEqualTo(actual.getTrademarkStatus()))
            .satisfies(
                e ->
                    assertThat(e.getCreatedDate())
                        .as("check createdDate")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getCreatedDate())
            )
            .satisfies(
                e ->
                    assertThat(e.getModifiedDate())
                        .as("check modifiedDate")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getModifiedDate())
            )
            .satisfies(e -> assertThat(e.getRenewalDate()).as("check renewalDate").isEqualTo(actual.getRenewalDate()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getPageNo()).as("check pageNo").isEqualTo(actual.getPageNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmUpdatableRelationshipsEquals(PublishedTm expected, PublishedTm actual) {
        assertThat(expected)
            .as("Verify PublishedTm relationships")
            .satisfies(e -> assertThat(e.getTmAgent()).as("check tmAgent").isEqualTo(actual.getTmAgent()));
    }
}
