package com.bassi.tmapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublishedTmPhoneticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsAllPropertiesEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertPublishedTmPhoneticsAutoGeneratedPropertiesEquals(expected, actual);
        assertPublishedTmPhoneticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsAllUpdatablePropertiesEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertPublishedTmPhoneticsUpdatableFieldsEquals(expected, actual);
        assertPublishedTmPhoneticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsAutoGeneratedPropertiesEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertThat(actual)
            .as("Verify PublishedTmPhonetics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsUpdatableFieldsEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertThat(actual)
            .as("Verify PublishedTmPhonetics relevant properties")
            .satisfies(a -> assertThat(a.getSanitizedTm()).as("check sanitizedTm").isEqualTo(expected.getSanitizedTm()))
            .satisfies(a -> assertThat(a.getPhoneticPk()).as("check phoneticPk").isEqualTo(expected.getPhoneticPk()))
            .satisfies(a -> assertThat(a.getPhoneticSk()).as("check phoneticSk").isEqualTo(expected.getPhoneticSk()))
            .satisfies(a -> assertThat(a.getComplete()).as("check complete").isEqualTo(expected.getComplete()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublishedTmPhoneticsUpdatableRelationshipsEquals(PublishedTmPhonetics expected, PublishedTmPhonetics actual) {
        assertThat(actual)
            .as("Verify PublishedTmPhonetics relationships")
            .satisfies(a -> assertThat(a.getPublishedTm()).as("check publishedTm").isEqualTo(expected.getPublishedTm()));
    }
}
