package com.bassi.tmapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TokenPhoneticAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenPhoneticAllPropertiesEquals(TokenPhonetic expected, TokenPhonetic actual) {
        assertTokenPhoneticAutoGeneratedPropertiesEquals(expected, actual);
        assertTokenPhoneticAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenPhoneticAllUpdatablePropertiesEquals(TokenPhonetic expected, TokenPhonetic actual) {
        assertTokenPhoneticUpdatableFieldsEquals(expected, actual);
        assertTokenPhoneticUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenPhoneticAutoGeneratedPropertiesEquals(TokenPhonetic expected, TokenPhonetic actual) {
        assertThat(actual)
            .as("Verify TokenPhonetic auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenPhoneticUpdatableFieldsEquals(TokenPhonetic expected, TokenPhonetic actual) {
        assertThat(actual)
            .as("Verify TokenPhonetic relevant properties")
            .satisfies(a -> assertThat(a.getAlgorithm()).as("check algorithm").isEqualTo(expected.getAlgorithm()))
            .satisfies(a -> assertThat(a.getPhoneticCode()).as("check phoneticCode").isEqualTo(expected.getPhoneticCode()))
            .satisfies(a ->
                assertThat(a.getSecondaryPhoneticCode()).as("check secondaryPhoneticCode").isEqualTo(expected.getSecondaryPhoneticCode())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenPhoneticUpdatableRelationshipsEquals(TokenPhonetic expected, TokenPhonetic actual) {
        assertThat(actual)
            .as("Verify TokenPhonetic relationships")
            .satisfies(a -> assertThat(a.getTrademarkToken()).as("check trademarkToken").isEqualTo(expected.getTrademarkToken()));
    }
}
