package com.bassi.tmapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrademarkTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenAllPropertiesEquals(TrademarkToken expected, TrademarkToken actual) {
        assertTrademarkTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertTrademarkTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenAllUpdatablePropertiesEquals(TrademarkToken expected, TrademarkToken actual) {
        assertTrademarkTokenUpdatableFieldsEquals(expected, actual);
        assertTrademarkTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenAutoGeneratedPropertiesEquals(TrademarkToken expected, TrademarkToken actual) {
        assertThat(actual)
            .as("Verify TrademarkToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenUpdatableFieldsEquals(TrademarkToken expected, TrademarkToken actual) {
        assertThat(actual)
            .as("Verify TrademarkToken relevant properties")
            .satisfies(a -> assertThat(a.getTokenText()).as("check tokenText").isEqualTo(expected.getTokenText()))
            .satisfies(a -> assertThat(a.getTokenType()).as("check tokenType").isEqualTo(expected.getTokenType()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenUpdatableRelationshipsEquals(TrademarkToken expected, TrademarkToken actual) {
        assertThat(actual)
            .as("Verify TrademarkToken relationships")
            .satisfies(a -> assertThat(a.getTrademark()).as("check trademark").isEqualTo(expected.getTrademark()));
    }
}
