package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TrademarkClassAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkClassAllPropertiesEquals(TrademarkClass expected, TrademarkClass actual) {
        assertTrademarkClassAutoGeneratedPropertiesEquals(expected, actual);
        assertTrademarkClassAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkClassAllUpdatablePropertiesEquals(TrademarkClass expected, TrademarkClass actual) {
        assertTrademarkClassUpdatableFieldsEquals(expected, actual);
        assertTrademarkClassUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkClassAutoGeneratedPropertiesEquals(TrademarkClass expected, TrademarkClass actual) {
        assertThat(actual)
            .as("Verify TrademarkClass auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkClassUpdatableFieldsEquals(TrademarkClass expected, TrademarkClass actual) {
        assertThat(actual)
            .as("Verify TrademarkClass relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getTmClass()).as("check tmClass").isEqualTo(expected.getTmClass()))
            .satisfies(a -> assertThat(a.getKeyword()).as("check keyword").isEqualTo(expected.getKeyword()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedDate())
            )
            .satisfies(a ->
                assertThat(a.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getModifiedDate())
            )
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkClassUpdatableRelationshipsEquals(TrademarkClass expected, TrademarkClass actual) {
        assertThat(actual)
            .as("Verify TrademarkClass relationships")
            .satisfies(a -> assertThat(a.getTrademarks()).as("check trademarks").isEqualTo(expected.getTrademarks()));
    }
}
