package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TrademarkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkAllPropertiesEquals(Trademark expected, Trademark actual) {
        assertTrademarkAutoGeneratedPropertiesEquals(expected, actual);
        assertTrademarkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkAllUpdatablePropertiesEquals(Trademark expected, Trademark actual) {
        assertTrademarkUpdatableFieldsEquals(expected, actual);
        assertTrademarkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkAutoGeneratedPropertiesEquals(Trademark expected, Trademark actual) {
        assertThat(expected)
            .as("Verify Trademark auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkUpdatableFieldsEquals(Trademark expected, Trademark actual) {
        assertThat(expected)
            .as("Verify Trademark relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDetails()).as("check details").isEqualTo(actual.getDetails()))
            .satisfies(e -> assertThat(e.getApplicationNo()).as("check applicationNo").isEqualTo(actual.getApplicationNo()))
            .satisfies(e -> assertThat(e.getApplicationDate()).as("check applicationDate").isEqualTo(actual.getApplicationDate()))
            .satisfies(e -> assertThat(e.getAgentName()).as("check agentName").isEqualTo(actual.getAgentName()))
            .satisfies(e -> assertThat(e.getAgentAddress()).as("check agentAddress").isEqualTo(actual.getAgentAddress()))
            .satisfies(e -> assertThat(e.getProprietorName()).as("check proprietorName").isEqualTo(actual.getProprietorName()))
            .satisfies(e -> assertThat(e.getProprietorAddress()).as("check proprietorAddress").isEqualTo(actual.getProprietorAddress()))
            .satisfies(e -> assertThat(e.getHeadOffice()).as("check headOffice").isEqualTo(actual.getHeadOffice()))
            .satisfies(e -> assertThat(e.getImgUrl()).as("check imgUrl").isEqualTo(actual.getImgUrl()))
            .satisfies(e -> assertThat(e.getTmClass()).as("check tmClass").isEqualTo(actual.getTmClass()))
            .satisfies(e -> assertThat(e.getJournalNo()).as("check journalNo").isEqualTo(actual.getJournalNo()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getUsage()).as("check usage").isEqualTo(actual.getUsage()))
            .satisfies(e -> assertThat(e.getAssociatedTms()).as("check associatedTms").isEqualTo(actual.getAssociatedTms()))
            .satisfies(e -> assertThat(e.getTrademarkStatus()).as("check trademarkStatus").isEqualTo(actual.getTrademarkStatus()))
            .satisfies(e ->
                assertThat(e.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedDate())
            )
            .satisfies(e ->
                assertThat(e.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getModifiedDate())
            )
            .satisfies(e -> assertThat(e.getRenewalDate()).as("check renewalDate").isEqualTo(actual.getRenewalDate()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getPageNo()).as("check pageNo").isEqualTo(actual.getPageNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkUpdatableRelationshipsEquals(Trademark expected, Trademark actual) {
        assertThat(expected)
            .as("Verify Trademark relationships")
            .satisfies(e -> assertThat(e.getUserProfile()).as("check userProfile").isEqualTo(actual.getUserProfile()));
    }
}
