package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TrademarkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkAllPropertiesEquals(Trademark expected, Trademark actual) {
        assertTrademarkAutoGeneratedPropertiesEquals(expected, actual);
        assertTrademarkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkAllUpdatablePropertiesEquals(Trademark expected, Trademark actual) {
        assertTrademarkUpdatableFieldsEquals(expected, actual);
        assertTrademarkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkAutoGeneratedPropertiesEquals(Trademark expected, Trademark actual) {
        assertThat(actual)
            .as("Verify Trademark auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkUpdatableFieldsEquals(Trademark expected, Trademark actual) {
        assertThat(actual)
            .as("Verify Trademark relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getApplicationNo()).as("check applicationNo").isEqualTo(expected.getApplicationNo()))
            .satisfies(a -> assertThat(a.getApplicationDate()).as("check applicationDate").isEqualTo(expected.getApplicationDate()))
            .satisfies(a -> assertThat(a.getAgentName()).as("check agentName").isEqualTo(expected.getAgentName()))
            .satisfies(a -> assertThat(a.getAgentAddress()).as("check agentAddress").isEqualTo(expected.getAgentAddress()))
            .satisfies(a -> assertThat(a.getProprietorName()).as("check proprietorName").isEqualTo(expected.getProprietorName()))
            .satisfies(a -> assertThat(a.getProprietorAddress()).as("check proprietorAddress").isEqualTo(expected.getProprietorAddress()))
            .satisfies(a -> assertThat(a.getHeadOffice()).as("check headOffice").isEqualTo(expected.getHeadOffice()))
            .satisfies(a -> assertThat(a.getImgUrl()).as("check imgUrl").isEqualTo(expected.getImgUrl()))
            .satisfies(a -> assertThat(a.getTmClass()).as("check tmClass").isEqualTo(expected.getTmClass()))
            .satisfies(a -> assertThat(a.getJournalNo()).as("check journalNo").isEqualTo(expected.getJournalNo()))
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a -> assertThat(a.getUsage()).as("check usage").isEqualTo(expected.getUsage()))
            .satisfies(a -> assertThat(a.getAssociatedTms()).as("check associatedTms").isEqualTo(expected.getAssociatedTms()))
            .satisfies(a -> assertThat(a.getTrademarkStatus()).as("check trademarkStatus").isEqualTo(expected.getTrademarkStatus()))
            .satisfies(a ->
                assertThat(a.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedDate())
            )
            .satisfies(a ->
                assertThat(a.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getModifiedDate())
            )
            .satisfies(a -> assertThat(a.getRenewalDate()).as("check renewalDate").isEqualTo(expected.getRenewalDate()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPageNo()).as("check pageNo").isEqualTo(expected.getPageNo()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getOrganizationType()).as("check organizationType").isEqualTo(expected.getOrganizationType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkUpdatableRelationshipsEquals(Trademark expected, Trademark actual) {
        assertThat(actual)
            .as("Verify Trademark relationships")
            .satisfies(a -> assertThat(a.getLead()).as("check lead").isEqualTo(expected.getLead()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getTrademarkPlan()).as("check trademarkPlan").isEqualTo(expected.getTrademarkPlan()))
            .satisfies(a -> assertThat(a.getTrademarkClasses()).as("check trademarkClasses").isEqualTo(expected.getTrademarkClasses()));
    }
}
