package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TrademarkTokenFrequencyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenFrequencyAllPropertiesEquals(TrademarkTokenFrequency expected, TrademarkTokenFrequency actual) {
        assertTrademarkTokenFrequencyAutoGeneratedPropertiesEquals(expected, actual);
        assertTrademarkTokenFrequencyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenFrequencyAllUpdatablePropertiesEquals(
        TrademarkTokenFrequency expected,
        TrademarkTokenFrequency actual
    ) {
        assertTrademarkTokenFrequencyUpdatableFieldsEquals(expected, actual);
        assertTrademarkTokenFrequencyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenFrequencyAutoGeneratedPropertiesEquals(
        TrademarkTokenFrequency expected,
        TrademarkTokenFrequency actual
    ) {
        assertThat(actual)
            .as("Verify TrademarkTokenFrequency auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenFrequencyUpdatableFieldsEquals(
        TrademarkTokenFrequency expected,
        TrademarkTokenFrequency actual
    ) {
        assertThat(actual)
            .as("Verify TrademarkTokenFrequency relevant properties")
            .satisfies(a -> assertThat(a.getFrequency()).as("check frequency").isEqualTo(expected.getFrequency()))
            .satisfies(a -> assertThat(a.getWord()).as("check word").isEqualTo(expected.getWord()))
            .satisfies(a ->
                assertThat(a.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedDate())
            )
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a ->
                assertThat(a.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getModifiedDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkTokenFrequencyUpdatableRelationshipsEquals(
        TrademarkTokenFrequency expected,
        TrademarkTokenFrequency actual
    ) {
        // empty method
    }
}
