package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.bigDecimalCompareTo;
import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TrademarkPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkPlanAllPropertiesEquals(TrademarkPlan expected, TrademarkPlan actual) {
        assertTrademarkPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertTrademarkPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkPlanAllUpdatablePropertiesEquals(TrademarkPlan expected, TrademarkPlan actual) {
        assertTrademarkPlanUpdatableFieldsEquals(expected, actual);
        assertTrademarkPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkPlanAutoGeneratedPropertiesEquals(TrademarkPlan expected, TrademarkPlan actual) {
        assertThat(actual)
            .as("Verify TrademarkPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkPlanUpdatableFieldsEquals(TrademarkPlan expected, TrademarkPlan actual) {
        assertThat(actual)
            .as("Verify TrademarkPlan relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getFees()).as("check fees").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFees()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a ->
                assertThat(a.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedDate())
            )
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a ->
                assertThat(a.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getModifiedDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrademarkPlanUpdatableRelationshipsEquals(TrademarkPlan expected, TrademarkPlan actual) {
        // empty method
    }
}
