package com.bassi.tmapp.domain;

import static com.bassi.tmapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class UserEventsTrackingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserEventsTrackingAllPropertiesEquals(UserEventsTracking expected, UserEventsTracking actual) {
        assertUserEventsTrackingAutoGeneratedPropertiesEquals(expected, actual);
        assertUserEventsTrackingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserEventsTrackingAllUpdatablePropertiesEquals(UserEventsTracking expected, UserEventsTracking actual) {
        assertUserEventsTrackingUpdatableFieldsEquals(expected, actual);
        assertUserEventsTrackingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserEventsTrackingAutoGeneratedPropertiesEquals(UserEventsTracking expected, UserEventsTracking actual) {
        assertThat(actual)
            .as("Verify UserEventsTracking auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserEventsTrackingUpdatableFieldsEquals(UserEventsTracking expected, UserEventsTracking actual) {
        assertThat(actual)
            .as("Verify UserEventsTracking relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getPageName()).as("check pageName").isEqualTo(expected.getPageName()))
            .satisfies(a -> assertThat(a.getDeviceType()).as("check deviceType").isEqualTo(expected.getDeviceType()))
            .satisfies(a ->
                assertThat(a.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedDate())
            )
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a ->
                assertThat(a.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getModifiedDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserEventsTrackingUpdatableRelationshipsEquals(UserEventsTracking expected, UserEventsTracking actual) {
        assertThat(actual)
            .as("Verify UserEventsTracking relationships")
            .satisfies(a -> assertThat(a.getUserProfile()).as("check userProfile").isEqualTo(expected.getUserProfile()));
    }
}
